dist: trusty
sudo: false

install: true

addons: 
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['expat', 'libgmp-dev', 'gcc-5', 'libpopt-dev']

language: java
jdk: oraclejdk8

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'

script :
 - ./tag.sh $FLAGS
 - ./install_tapaal.sh
 - mkdir -p logs/oracle/
 - (rc=0 ; for MODEL in oracle/*RD.out ; do ./run_test.pl $MODEL -tapaal || rc=$? ; done; exit $rc) 
 - tar czf logs.tgz logs/
 - mv logs.tgz website/

# 2> logs/$MODEL.err | tee logs/$MODEL.out | grep test 

#cache:
#  directories:
#    - eclipse/
    
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: website/
#  on:
#    branch: master
